name: tutopedia
description: A e-learning apps for students.

publish_to: "none"

version: 1.0.8+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.1
  email_validator: ^2.1.17
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  salomon_bottom_bar: ^3.3.1
  pod_player: ^0.1.0
  package_info_plus: ^3.0.3
  path_provider: ^2.0.13
  image_picker: ^0.8.6+4
  fluttertoast: ^8.2.1
  flutter_rating_bar: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^6.3.1
  adaptive_theme: ^3.2.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
